#include "velocity3D_system.c"
#include "acceleration3D_system.c"
#include "omega3D_system.c"
#include "alpha3D_system.c"
#include "friction3D_system.c"
#include "dissipation3D_system.c"
#include "gravity3D_system.c"
#include "jump3D_system.c"
#include "physics3D_disable_system.c"
#include "random_jump3D_system.c"
#include "position3D_bounds_system.c" //  move to transforms

void define_systems_physics3D(ecs_world_t *world) {
    zox_system(Velocity3DSystem, zox_pip_physics,
        [out] transforms3.d.Position3D,
        [in] core.physics3.d.Velocity3D)
    zox_system(Omega3DSystem, zox_pip_physics,
        [in] Omega3D,
        [out] transforms3.d.Rotation3D)
    zox_system(Physics3DDisableSystem, zox_pip_physics,
        [out] InitializePhysics3D,
        [out] transforms3.d.Position3D,
        [out] core.physics3.d.Velocity3D)
    zox_system(Gravity3DSystem, zox_pip_physics,
        [in] Gravity3D,
        [in] core.physics3.d.Grounded,
        [out] core.physics3.d.Acceleration3D)
    zox_system(RandomJump3DSystem, zox_pip_physics,
        [in] core.physics3.d.Grounded,
        [out] Jump,
        [none] Jumper)
    zox_system(Jump3DSystem, zox_pip_physics,
        [in] physics.DisableMovement,
        [in] core.physics3.d.Velocity3D,
        [out] Jump,
        [out] core.physics3.d.Acceleration3D)
    zox_system(Friction3DSystem, zox_pip_physics,
        [in] core.physics3.d.Grounded,
        [in] core.physics3.d.Velocity3D,
        [out] core.physics3.d.Acceleration3D,
        [none] physics.Frictioned)
    zox_system(Dissipation3DSystem, zox_pip_physics,
        [none] physics.Frictioned,
        [in] Omega3D,
        [out] Alpha3D)
    zox_system(Acceleration3DSystem, zox_pip_physics,
        [out] core.physics3.d.Acceleration3D,
        [out] core.physics3.d.Velocity3D)
    zox_system(Alpha3DSystem, zox_pip_physics,
        [out] Alpha3D,
        [out] Omega3D)
    zox_system(Position3DBoundsSystem, zox_pip_physics,
        [in] generic.Position3DBounds,
        [in] generic.Bounds3D,
        [out] transforms3.d.Position3D)
}