zox_component_byte(MenuType)    // index for menus
zox_declare_tag(MenuMain)
zox_declare_tag(MenuOptions)
zox_declare_tag(MenuPaused)
zox_declare_tag(MenuGame)
zox_declare_tag(MenuGameTouch)
zox_declare_tag(MenuStart)
zox_declare_tag(FPSDisplay)
zox_declare_tag(QuadsCountLabel)
zox_declare_tag(GameDebugLabel)
zox_declare_tag(Profiler)
zox_declare_tag(Taskbar)
zox_declare_tag(MenuNewRealm)
zox_component_byte(HitType)
zox_component_int(QuadsCount)
zox_component_double(FPSDisplayTicker)
#include "debug_label_data.c"

void define_components_game_ui(ecs_world_t *world) {
    zox_define_component_byte(MenuType)
    zox_define_tag(MenuMain)
    zox_define_tag(MenuOptions)
    zox_define_tag(MenuPaused)
    zox_define_tag(MenuGame)
    zox_define_tag(MenuGameTouch)
    zox_define_tag(MenuStart)
    zox_define_tag(FPSDisplay)
    zox_define_tag(QuadsCountLabel)
    zox_define_tag(GameDebugLabel)
    zox_define_tag(Profiler)
    zox_define_tag(Taskbar)
    zox_define_tag(MenuNewRealm);
    zox_define_component_byte(HitType)
    zox_define_component_int(QuadsCount)
    zox_define_component_double(FPSDisplayTicker)
    zox_define_component(DebugLabelData)
}