zox_tag(Device);
zox_tag(Zevice);
zox_tag(Gamepad);
zox_tag(Touchscreen);
zox_tag(Mouse);
zox_tag(Finger);
zoxc_byte(DeviceDisabled);
zoxc_byte(ZeviceDisabled);
zoxc_byte(ZeviceButton);
zoxc_byte(ZevicePointer);
zoxc_byte(ZevicePointerOld);
zoxc_byte(ZevicePointerRight);
zoxc_byte(DeviceButtonType);
zoxc_byte(RealButtonIndex);
zoxc_byte(DeviceLayout);
zoxc_byte(MouseLock);
zoxc_byte(DeviceMode);
zoxc_byte(DeviceModeDirty);
zoxc_float2(ZeviceStick);
zoxc_int2(ZevicePointerPosition);
zoxc_int2(ZevicePointerDelta);
zoxc_int2(ZeviceWheel);
zoxc_entity(DeviceLink);
zoxc_entity(MouseLink);
zoxc_entity(ZeviceLink);
zoxc_entity(VirtualZeviceLink);
zoxc_arrayd(DeviceButtonLinks, entity)
zoxc_entities(DeviceLinks)
#include "keyboard.c"

void define_components_inputs(ecs *world) {
    zox_define_tag(Device);
    zox_define_tag(Zevice);
    zox_define_tag(Gamepad);
    zox_define_tag(Touchscreen);
    zox_define_tag(Finger);
    zox_define_tag(Mouse);
    zox_define_component(Keyboard);
    zoxd_byte(DeviceDisabled);
    zoxd_byte(ZeviceDisabled);
    zoxd_byte(ZevicePointer);
    zoxd_byte(ZevicePointerOld);
    zoxd_byte(ZevicePointerRight);
    zoxd_byte(ZeviceButton);
    zoxd_byte(DeviceButtonType);
    zoxd_byte(RealButtonIndex);
    zoxd_byte(DeviceLayout);
    zoxd_byte(MouseLock);
    zoxd_byte(DeviceMode);
    zoxd_byte(DeviceModeDirty);
    zox_define_component_int2(ZevicePointerPosition);
    zox_define_component_int2(ZevicePointerDelta);
    zox_define_component_int2(ZeviceWheel);
    zox_define_component_float2(ZeviceStick);
    zox_define_component_entity(DeviceLink);
    zox_define_component_entity(MouseLink);
    zox_define_component_entity(ZeviceLink);
    zox_define_component_entity(VirtualZeviceLink);
    zox_define_entities_component(DeviceLinks);
}