//! An entity can have a unique ID generated by guid or something.
typedef struct PhysicalButton
{
    unsigned char wasPressedThisFrame;
    unsigned char isPressed;
    unsigned char wasReleasedThisFrame;
} PhysicalButton;