//! An entity can have a unique ID generated by guid or something.
typedef struct
{
    unsigned char is_pressed;
    unsigned char pressed_this_frame;
    unsigned char released_this_frame;
} PhysicalButton;