#include "euler_override_system.c"
#include "parent_position_system.c"
#include "parent_rotation_system.c"
#include "euler_limit_x_system.c"
#include "euler_limit_z_system.c"
#include "transform_matrix_system.c"
#include "transform_matrix_scale_system.c"
#include "camera_transform_matrix_system.c"

void zox_define_systems_transforms3D(ecs_world_t *world) {
    zox_system(EulerLimitXSystem, EcsOnUpdate,
        [in] EulerLimitX,
        [out] Euler)
    zox_system(EulerLimitZSystem, EcsOnUpdate,
        [in] EulerLimitZ,
        [out] Euler)
    zox_system(EulerOverrideSystem, EcsOnUpdate,
        [none] EulerOverride,
        [in] Euler,
        [out] Rotation3D)
    zox_system(ParentRotationSystem, zox_transforms_stage,
        [in] hierarchys.ParentLink,
        [in] LocalRotation3D,
        [out] Rotation3D)
    zox_system(ParentPositionSystem, zox_transforms_stage,
        [in] hierarchys.ParentLink,
        [in] LocalPosition3D,
        [out] Position3D)
    zox_system(TransformMatrixSystem, zox_transforms_stage,
        [in] Position3D,
        [in] Rotation3D,
        [out] TransformMatrix,
        [none] !transforms.Scale1D)
    zox_system(TransformMatrixScaleSystem, zox_transforms_stage,
        [in] Position3D,
        [in] Rotation3D,
        [in] transforms.Scale1D,
        [out] TransformMatrix)
}