//! An entity can have a unique ID generated by guid or something.
/**
*   \todo Use a hashmap with keys keyboard->keys['a'] for more dynamic access.
*/
typedef struct
{
    int2 position;
    int2 delta;
    PhysicalButton left;
    PhysicalButton middle;
    PhysicalButton right;
} Mouse;
ECS_COMPONENT_DECLARE(Mouse);