zox_tag(Label);
zox_tag(Button);
zox_tag(CloseButton);
zox_tag(Icon);
zox_tag(Frame);
zox_tag(IconLabel);
zox_tag(IconOverlay);
zox_tag(Header);
zox_tag(Body);
zox_tag(Scrollbar);
zox_tag(ScrollbarButton);
zox_tag(Elementbar2D);
zoxc_byte(IconType);
zoxc_byte(ListUIMax);
zoxc_byte(IconIndex);
zoxc_entity(FramePrefabLink);
zoxc_float2(SlideBounds);
zoxc(SliderLabel, const char*);

void define_components_elements2D(ecs *world) {
    zox_define_tag(Label);
    zox_define_tag(Button);
    zox_define_tag(Icon);
    zox_define_tag(Frame);
    zox_define_tag(IconLabel);
    zox_define_tag(IconOverlay);
    zox_define_tag(Header);
    zox_define_tag(Body);
    zox_define_tag(CloseButton);
    zox_define_tag(Scrollbar);
    zox_define_tag(ScrollbarButton);
    zox_define_tag(Elementbar2D);
    zoxd_byte(IconType);
    zoxd_byte(ListUIMax);
    zoxd_byte(IconIndex);
    zox_define_component_entity(FramePrefabLink);
    zox_define_component_float2(SlideBounds);
    zox_define_component(SliderLabel);
}