zox_declare_tag(Zext)
zox_declare_tag(ZextLabel)
zox_declare_tag(ZextRenderEnabler)
zox_declare_tag(Text2D)
zox_component_byte(ZextDirty)
zox_component_byte(ZextAlignment)
zox_component_byte(TextResolution)
zox_component_byte2(TextPadding)
zox_component_int(TextSize)
zox_component_double(AnimateZext)
zox_component_zext(TextData)

void zox_define_components_texts(ecs_world_t *world) {
    zox_define_tag(Zext)
    zox_define_tag(ZextLabel)
    zox_define_tag(ZextRenderEnabler)
    zox_define_tag(Text2D)
    zox_define_component_byte(ZextDirty)
    zox_define_component_byte(ZextAlignment)
    zox_define_component_byte(TextResolution)
    zox_define_component_byte2(TextPadding)
    zox_define_component_int(TextSize)
    zox_define_component_double(AnimateZext)
    zox_define_component_zext(TextData)
}