zox_declare_tag(Mesh)
zox_component_byte(MeshDirty)
zox_component_entity(MeshLink)
zox_component_byte(TextureDirty)
zox_component_byte(MeshAlignment)
zox_component_byte(RenderLod)
zox_component_byte(RenderDistance)
zox_component_byte(RenderDisabled)
zox_component_float(Brightness)
zox_component_float(Alpha)
zox_component_entity(MaterialLink)

void define_components_rendering(ecs_world_t *world) {
    zox_define_tag(Mesh)
    zox_define_component_byte(MeshDirty)
    zox_define_component_byte(MeshAlignment)
    zox_define_component_entity(MeshLink)
    zox_define_component_byte(TextureDirty)
    zox_define_component_byte(RenderLod)
    zox_define_component_byte(RenderDistance)
    zox_define_component_byte(RenderDisabled)
    zox_define_component_float(Brightness)
    zox_define_component_float(Alpha)
    zox_define_component_entity(MaterialLink)
}