# # Declare compiler tools and flags
# CFLAGS = cc
# CFLAGS += -std=c99
# CFLAGS += -fPIC
# CFLAGS += -g
# # Add libraries
# LDLIBS = -lGL
# LDLIBS += -lSDL2
# LDLIBS += -lSDL2_image
# # Compiler Optimizations
# LDLIBS += -O3
# LDLIBS += -flto
# # Removes Debug Messages
# LDLIBS += -D NDEBUG
# # SRC FILES
# SRCS = 
# # Rendering Make File
# SRCS += Rendering.h
# SRCS += Core/RenderingCore.h
# # OBJs
# OBJS = 
# OBJS += Rendering.h

# rendering.o: $(SRCS)
# 	$(CFLAGS) -o $@ $(OBJS) $(LDLIBS)