#ifndef Zoxel_Core
#define Zoxel_Core

#ifndef M_PI
#define M_PI 3.141592653589793
#endif
#ifndef degreesToRadians
#define degreesToRadians (M_PI * 2) / 360.0f
#endif
// libraries
#include <stdlib.h>
#include <stdio.h>
#include <math.h> // for sqrt
// util
#include "Util/flecs_macros.c"
#include "Util/flecs_extensions.c"
// Data
// move this to math module?
#include "Data/float2.c"
#include "Data/float3.c"
#include "Data/float4.c"
#include "Data/float4x4.c"
#include "Data/double2.c"
#include "Data/int2.c"
#include "Data/color.c"
// Util
#include "Util/math.c"
// Components
//! An entity can have a unique ID generated by guid or something.
zoxel_component(EntityDirty, unsigned char);
//! An entity can have a unique ID generated by guid or something.
zoxel_component(ID, int);
//! An entity can have a unique ID generated by guid or something.
zoxel_component(Seed, long int);
// Systems
#include "Systems/EntityDirtyResetSystem.c"

void CoreImport(ecs_world_t *world)
{
    ECS_MODULE(world, Core);
    ECS_COMPONENT_DEFINE(world, EntityDirty);
    ECS_COMPONENT_DEFINE(world, ID);
    ECS_COMPONENT_DEFINE(world, Seed);
    ECS_SYSTEM_DEFINE(world, EntityDirtyResetSystem, EcsPostUpdate, [out] EntityDirty);
}

#endif