//! An entity can have a unique ID generated by guid or something.
/**
*   \todo Use a hashmap with keys keyboard->keys['a'] for more dynamic access.
*/
typedef struct {
    int2 position;
    int2 delta;
    int2 wheel;
    PhysicalButton left;
    PhysicalButton middle;
    PhysicalButton right;
} Mouse;
zoxel_custom_component(Mouse)

#define mouse_zero {\
    (int2) { 0, 0 },\
    (int2) { 0, 0 },\
    (int2) { 0, 0 },\
    (PhysicalButton) { 0, 0, 0 },\
    (PhysicalButton) { 0, 0, 0 },\
    (PhysicalButton) { 0, 0, 0 }\
}
