#ifndef zoxel_generic
#define zoxel_generic

// libraries
#include <stdlib.h>
#include <stdio.h>
// util
#include "util/flecs_macros.c"
#include "util/flecs_extensions.c"
// move this to math module?
#include "data/color.c"
// components
//! An entity can have a unique ID generated by guid or something.
zoxel_component(EntityDirty, unsigned char);
//! An entity can have a unique ID generated by guid or something.
zoxel_component(ID, int);
//! An entity can have a unique ID generated by guid or something.
zoxel_component(Seed, long int);
// systems
#include "systems/entity_dirty_reset_system.c"
// util
#include "util/generic_util.c"

void GenericImport(ecs_world_t *world)
{
    ECS_MODULE(world, Generic);
    ECS_COMPONENT_DEFINE(world, EntityDirty);
    ECS_COMPONENT_DEFINE(world, ID);
    ECS_COMPONENT_DEFINE(world, Seed);
    ECS_SYSTEM_DEFINE(world, EntityDirtyResetSystem, EcsPostUpdate, [out] EntityDirty);
}
#endif