#ifndef zoxel_generic
#define zoxel_generic

// libraries
#include <stdlib.h>
#include <stdio.h>
// util
#include "util/flecs_macros.c"
#include "util/flecs_system_macros.c"
#include "util/flecs_extensions.c"
// move this to math module?
#include "data/color.c"
// Tags
ECS_DECLARE(Selectable);
ECS_DECLARE(Clickable);
// event components
//! An entity can have a unique ID generated by guid or something.
zoxel_component(EntityDirty, unsigned char);
zoxel_component(EntityInitialize, unsigned char);
//! The raycasted entity state.
zoxel_component(SelectableState, unsigned char);
//! The raycasted entity state.
zoxel_component(ClickableState, unsigned char);
// components
//! An entity can have a unique ID generated by guid or something.
zoxel_component(ID, int);
//! An entity can have a unique ID generated by guid or something.
zoxel_component(Seed, long int);
//! Contains the raycast mouse position.
zoxel_component(Raycaster, int2);
//! A target entity for the Raycaster.
zoxel_component(RaycasterTarget, ecs_entity_t);
// systems
zoxel_reset_system(EntityDirtyResetSystem, EntityDirty)
zoxel_reset_system(ClickableStateResetSystem, ClickableState)
zoxel_reset_system(EntityInitializeResetSystem, EntityInitialize)
// util
#include "util/generic_util.c"

void GenericImport(ecs_world_t *world)
{
    ECS_MODULE(world, Generic);
    ECS_TAG_DEFINE(world, Selectable);
    ECS_TAG_DEFINE(world, Clickable);
    ECS_COMPONENT_DEFINE(world, EntityDirty);
    ECS_COMPONENT_DEFINE(world, SelectableState);
    ECS_COMPONENT_DEFINE(world, ClickableState);
    ECS_COMPONENT_DEFINE(world, ID);
    ECS_COMPONENT_DEFINE(world, Seed);
    ECS_COMPONENT_DEFINE(world, Raycaster);
    ECS_COMPONENT_DEFINE(world, RaycasterTarget);
    ECS_COMPONENT_DEFINE(world, EntityInitialize);
    zoxel_reset_system_define(EntityDirtyResetSystem, EntityDirty);
    zoxel_reset_system_define(ClickableStateResetSystem, ClickableState);
    zoxel_reset_system_define(EntityInitializeResetSystem, EntityInitialize);
}
#endif