#include "player3D_move_system.c"
#include "player3D_rotate_system.c"
#include "player3D_jump_system.c"
#include "player3D_trigger_system.c"
#include "jump3D_system.c"
#include "random_jump3D_system.c"
#include "can_jump_system.c"
#include "player3_respawn_system.c"

void define_systems_controllers3D(ecs_world_t *world) {
    zox_system(Player3DMoveSystem, zox_pip_player_movement,
        [in] inputs.DeviceLinks,
        [in] inputs.DeviceMode,
        [in] characters.CharacterLink,
        [none] players.Player)
    zox_system(Player3RotateSystem, zox_pip_player_movement,
        [in] inputs.DeviceLinks,
        [in] inputs.DeviceMode,
        [in] characters.CharacterLink,
        [in] cameras.CameraLink,
        [none] players.Player)
    zox_system(Player3DJumpSystem, zox_pip_player_movement,
        [in] inputs.DeviceLinks,
        [in] inputs.DeviceMode,
        [in] characters.CharacterLink,
        [none] players.Player)
    zox_system(Player3DTriggerSystem, EcsPostUpdate,
        [in] inputs.DeviceLinks,
        [in] inputs.DeviceMode,
        [in] characters.CharacterLink,
        [none] players.Player)
    zox_system(Jump3System, zox_pip_physics,
        [in] physics.DisableMovement,
        [out] physics3.Velocity3D,
        [out] characters.Jump,
        [out] physics3.Acceleration3D)
    zox_system(RandomJump3DSystem, zox_pip_physics,
        [in] collisions3.Grounded,
        [out] characters.Jump,
        [none] npcs.Jumper)
    zox_system(CanJumpSystem, EcsOnUpdate,
        [in] collisions3.Grounded,
        [in] characters.CanJump)
    zox_system_1(Player3RespawnSystem, EcsOnUpdate,
        [out] players.PlayerState,
        [out] players.PlayerRespawn,
        [out] characters.CharacterLink);
}